Aayam/Controllers/CourseController.cs
using DAL.Repositories.Master.Interface;
using DAL.Repositories.Master.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.MasterDetails;

namespace Aayam.Controllers
{
    public class CourseController : Controller
    {
        private readonly IDCourse _idCourse;
        public CourseController()
        {
            _idCourse = new DCourse();
        }

        public ActionResult CourseSelect()
        {
            ModelState.Clear();
            return View(_idCourse.CourseSelect());
        }

        public ActionResult CourseInsert()
        {
            ViewBag.Streams = _idCourse.BindStream();
            return View();
        }

        [HttpPost]
        public ActionResult CourseInsert(Course objCourse)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_idCourse.CourseInsert(objCourse))
                    {
                        ViewBag.Message =true;
                    }
                }
                ViewBag.Streams = _idCourse.BindStream();
                ModelState.Clear();
                return View();
               
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CourseUpdate(int id)
        {
            ViewBag.Streams = _idCourse.BindStream();
            return View(_idCourse.CourseSelect().Find(str => str.CourseID == id));
        }

        [HttpPost]
        public ActionResult CourseUpdate(int id, Course objCourse)
        {
            try
            {
                if (_idCourse.CourseUpdate(id, objCourse))
                {
                    ViewBag.message = true;
                }
                return RedirectToAction("CourseSelect");
            }
            catch
            {
                return View();
            }
        }


        //public ActionResult BindStream()
        //{
        //    ModelState.Clear();
        //    return View(_idCourse.BindStream());
        //}
    }
}

Aayam/Views/Course/CourseInsert.cshtml
@model ViewModel.MasterDetails.Course


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Course</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("CourseSelect", "Course")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Course</h3>
                </div>
                <div class="panel-body">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)
                            <div class="row">
                                @Html.LabelFor(model => model.CourseName, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.TextBoxFor(model => model.CourseName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                @Html.LabelFor(model => model.StreamID, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.DropDownListFor(model => model.StreamID, (ViewBag.Streams as List<ViewModel.MasterDetails.Streams>).Select(x => new SelectListItem() { Text = x.StreamName, Value = x.StreamID.ToString() }), "--SELECT--", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row example example-buttons">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                            @if (ViewBag.Message == true)
                            {
                                <div class="alert alert-success">
                                    <strong>Course has been added!</strong>
                                </div>
                            }
                        </div>
                        <div class="clearfix hidden-xs">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aayam/Views/Course/CourseSelect.cshtml
@model IEnumerable<ViewModel.MasterDetails.CourseViewModel>

@*<p>
        @Html.ActionLink("Create New", "CourseInsert")
    </p>*@
<div class="page ">
    <div class="page-header">
        <h1 class="page-title">Course</h1>
        <div class="page-header-actions">
            <a href="@Url.Action("CourseInsert", "Course")"><input type="button" value="Add Course" class="btn btn-primary" /></a>
        </div>
    </div>
    <div class="page-content">
        <!-- Panel Form Elements -->
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Course List</h3>
            </div>
            <div class="panel-body container-fluid">

                <table class="table table-striped table-bordered table-hover" id="CourseTable">
                    <thead class="thead-default">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CourseName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Stream)
                            </th>
                            <th></th>
                        </tr>
                        </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CourseName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Stream)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "CourseUpdate", new { id = item.CourseID }) |
                                    @Html.ActionLink("Delete", "CourseDelete", new { id = item.CourseID }, new { onclick = "return confirm('Are you sure you wish to delete this Course?');" })
                                </td>
                            </tr>
                        }
                    </tbody>

</table>
            </div>
        </div>

    </div>
</div>
<script>
    $(document).ready(function () {
        $('#CourseTable').DataTable();
    });
</script>

Aayam/Views/Course/CourseUpdate.cshtml
@model ViewModel.MasterDetails.CourseViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Course</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("CourseSelect", "Course")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Update Course</h3>
                </div>
                <div class="panel-body">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.CourseID)

                            <div class="row">
                                @Html.LabelFor(model => model.CourseName, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.TextBoxFor(model => model.CourseName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                @Html.LabelFor(model => model.StreamID, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.DropDownListFor(model => model.StreamID, (ViewBag.Streams as List<ViewModel.MasterDetails.Streams>).Select(x => new SelectListItem() { Text = x.StreamName, Value = x.StreamID.ToString() }), "--SELECT--", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row example example-buttons">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="btn btn-primary"  />
                                </div>
                            </div>
                        </div>
                        <div class="clearfix hidden-xs">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CourseSelect")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}