Aayam/Controllers/MasterController.cs
using DAL.Repositories.Admin.Interface;
using DAL.Repositories.Admin.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.MasterDetails;

namespace Aayam.Controllers
{
    public class MasterController : Controller
    {
        private readonly IDAddMasterDetails _idAddMasterDetails;
        public MasterController()
        {
            _idAddMasterDetails = new DAddmasterDetails();
        }

        public ActionResult GetAllStreams()
        {
            ModelState.Clear();
            return View(_idAddMasterDetails.GetAllStreams());
        }
      
        public ActionResult AddStream()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddStream(Streams objStream)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_idAddMasterDetails.addStream(objStream))
                    {
                        ViewBag.Message =true;
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

      
        public ActionResult updateStream(int id)
        {
          
            return View(_idAddMasterDetails.GetAllStreams().Find(str => str.StreamID == id));

        }
      
        [HttpPost]
        public ActionResult updateStream(int id, Streams objStream)
        {
            try
            {
                if ( _idAddMasterDetails.UpdateStream(id,objStream))
                {
                    ViewBag.message = true;  
                }
                return RedirectToAction("GetAllStreams");
            }
            catch
            {
                return View();
            }
        }
      
        public ActionResult DeleteStream(int id)
        {
            try
            {
              
                if (_idAddMasterDetails.DeleteStream(id))
                {
                    ViewBag.message = true;

                }
                return RedirectToAction("GetAllStreams");

            }
            catch
            {
                return View();
            }
        }  
    
    }
}

Aayam/Views/Master/AddStream.cshtml
@model ViewModel.MasterDetails.Streams


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Streams</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("GetAllStreams", "Master")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Stream</h3>
                </div>
                <div class="panel-body container-fluid">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)
                            <div class="row">
                                <div class="col-sm-2">
                                    @Html.LabelFor(model => model.StreamName, new { @class = "control-label" })
                                </div>
                                <div class="form-group col-sm-4">
                                    @Html.TextBoxFor(model => model.StreamName,null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamName)
                                </div>
                            </div>
                            <div class="row example example-buttons">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                            @if (ViewBag.Message == true)
                            {
                                <div class="alert alert-success">
                                    <strong>Stream has been added!</strong>
                                </div>
                            }
                        </div>
                        <div class="clearfix hidden-xs">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}



@*<div>
        @Html.ActionLink("Back to List", "GetAllStreams")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aayam/Views/Master/GetAllStreams.cshtml
@model IEnumerable<ViewModel.MasterDetails.Streams>



<div class="page ">
    <div class="page-header">
        <h1 class="page-title">Stream</h1>
        <div class="page-header-actions">
            <a href="@Url.Action("addStream", "Master")"><input type="button" value="Add Stream" class="btn btn-primary" /></a>
        </div>
    </div>
    <div class="page-content">
        <!-- Panel Form Elements -->
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Stream List</h3>
            </div>
            <div class="panel-body container-fluid">

                <table class="table table-striped table-bordered table-hover" id="streamTable">
                    <thead class="thead-default">
                        <tr>
                            @*<th class="studentHeader">
        @Html.DisplayNameFor(model => model.StreamID)
    </th>*@
                            <th class="studentHeader">
                                @Html.DisplayNameFor(model => model.StreamName)
                            </th>
                            <th class="studentHeader">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @*<td>
                            @Html.DisplayFor(modelItem => item.StreamID)
                        </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.StreamName)
                                </td>
                                <td>

                                    @Html.ActionLink("Edit", "updateStream", new { id = item.StreamID }, new { @class = "btn-outline" }) |

                                    @*@Html.ActionLink("Delete", "DeleteStream", new { id = item.StreamID })*@
                                    @Html.ActionLink("Delete", "DeleteStream", new { id = item.StreamID }, new { onclick = "return confirm('Are you sure you wish to delete this Stream?');" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
<script>
    $(document).ready(function () {
        $('#streamTable').DataTable();
    });
</script>

Aayam/Views/Master/updateStream.cshtml
@model ViewModel.MasterDetails.Streams


@using (Html.BeginForm("updateStream", "Master", FormMethod.Post,
                                      new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Streams</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("GetAllStreams", "Master")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Update Stream</h3>
                </div>
                <div class="panel-body container-fluid">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)

                            <div class="row">
                                @Html.LabelFor(model => model.StreamName, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.TextBoxFor(model => model.StreamName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamName)
                                </div>
                            </div>

                            <div class="row example example-buttons">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}